# Generated by Django 5.1.4 on 2025-02-20 14:52

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SavingGoals",
            new_name="SavingGoal",
        ),
        migrations.AlterField(
            model_name="expense",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 2, 20, 14, 52, 22, 305352, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="income",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 2, 20, 14, 52, 22, 305352, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
