# Generated by Django 5.1.4 on 2025-03-03 21:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_expense_date_alter_income_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="income",
            old_name="source",
            new_name="name",
        ),
        migrations.AlterField(
            model_name="expense",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 3, 3, 21, 7, 34, 924863, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="income",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 3, 3, 21, 7, 34, 923848, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
