# Generated by Django 5.1.2 on 2025-03-06 12:27

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_is_necssity_expense_is_necessity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SavingGoal',
            new_name='Goal',
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 6, 12, 25, 46, 362996, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 6, 12, 25, 46, 362996, tzinfo=datetime.timezone.utc)),
        ),
    ]
